# Generated by Django 4.1 on 2023-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_code",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
