# Generated by Django 4.1 on 2023-03-31 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_phone_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_code",
        ),
    ]
