# Generated by Django 4.1 on 2023-07-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_user_phone_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fullName",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="national_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
