# Generated by Django 4.1 on 2023-07-01 10:05

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=72)),
                (
                    "logo",
                    models.ImageField(upload_to=brand.models.brand_logo_file_path),
                ),
            ],
        ),
    ]
