# Generated by Django 4.1 on 2024-05-13 19:47

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brand", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "برند", "verbose_name_plural": "برندها"},
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                upload_to=brand.models.brand_logo_file_path, verbose_name="لوگو"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="title",
            field=models.CharField(max_length=72, verbose_name="عنوان"),
        ),
    ]
