# Generated by Django 4.1 on 2023-07-03 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
