# Generated by Django 4.1 on 2023-08-02 19:03

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.category_logo_file_path
            ),
        ),
    ]
