# Generated by Django 4.1 on 2023-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_category_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_cart",
            field=models.BooleanField(default=False),
        ),
    ]
