# Generated by Django 4.1 on 2023-08-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0001_initial"),
        ("store", "0008_paymentmethod_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="discount.discountcode",
            ),
        ),
    ]
