# Generated by Django 4.1 on 2023-08-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_product_technical_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="technical_number",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
