# Generated by Django 4.1 on 2024-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_orderitem_technical_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="image_url",
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تکمیل شده"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="doing_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ در دست اقدام"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ لغو شده"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="registered_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ ثبت سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("P", "در انتظار بررسی (پرداخت شده)"),
                    ("D", "تکمیل شده"),
                    ("C", "لغو شده / پر داخت ناموفق"),
                    ("DD", "در دست اقدام"),
                ],
                default="P",
                max_length=2,
            ),
        ),
    ]
