# Generated by Django 4.1 on 2024-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_remove_orderitem_image_url_order_confirmed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.BigIntegerField(null=True),
        ),
    ]
