# Generated by Django 4.1 on 2024-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
