# Generated by Django 4.1 on 2024-05-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("province", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "شهر", "verbose_name_plural": "شهر ها"},
        ),
        migrations.AlterModelOptions(
            name="province",
            options={"verbose_name": "استان", "verbose_name_plural": "استان ها"},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=85, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="province.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(max_length=225, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=50, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="province",
            name="slug",
            field=models.SlugField(max_length=125, verbose_name="اسلاگ"),
        ),
    ]
