# Generated by Django 4.1 on 2024-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcode",
            options={"verbose_name": "تخفیف", "verbose_name_plural": "تخفیفات"},
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(max_length=25, verbose_name="کد"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="count",
            field=models.IntegerField(default=0, verbose_name="تعداد قابل مصرف"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="end_date",
            field=models.DateField(verbose_name="زمان انقضاء"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="percentage",
            field=models.IntegerField(default=0, verbose_name="درصد"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="reason",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="علت تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="start_date",
            field=models.DateField(verbose_name="زمان شروع"),
        ),
    ]
