# Generated by Django 4.1 on 2023-08-08 17:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
        ("brand", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("desc", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="brand.brand",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(related_name="cars", to="gallery.gallery"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car_Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=125)),
                ("value", models.CharField(max_length=225)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="car.car",
                    ),
                ),
            ],
        ),
    ]
