# Generated by Django 4.1 on 2024-05-13 19:47

import car.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
        ("brand", "0002_alter_brand_options_alter_brand_logo_and_more"),
        ("car", "0002_car_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "ماشین", "verbose_name_plural": "ماشین ها"},
        ),
        migrations.AlterModelOptions(
            name="car_specification",
            options={
                "verbose_name": "مشخصه ماشین",
                "verbose_name_plural": "مشخصات ماشین ها",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="brand.brand",
                verbose_name="برند",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="desc",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="gallery",
            field=models.ManyToManyField(
                related_name="cars", to="gallery.gallery", verbose_name="گالری"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                upload_to=car.models.car_image_file_path, verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="title",
            field=models.CharField(max_length=150, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="car_specification",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="car.car",
                verbose_name="ماشین",
            ),
        ),
        migrations.AlterField(
            model_name="car_specification",
            name="key",
            field=models.CharField(max_length=125, verbose_name="مشخصه"),
        ),
        migrations.AlterField(
            model_name="car_specification",
            name="value",
            field=models.CharField(max_length=225, verbose_name="مقدار"),
        ),
    ]
