# Generated by Django 4.1 on 2023-06-10 21:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=85)),
                ("slug", models.SlugField(max_length=170)),
                ("short_desc", models.CharField(blank=True, max_length=300, null=True)),
                ("desc", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("image_alt", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("TS", "مشخصات فنی"), ("FE", "امکانات و تجهیزات")],
                        default="TS",
                        max_length=2,
                    ),
                ),
                ("key", models.CharField(max_length=125)),
                ("value", models.TextField()),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("image_alt", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_categories",
                        to="gallery.gallery",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blogs",
                to="gallery.gallery",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
