# Generated by Django 4.1 on 2023-06-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blogs",
                to="gallery.gallery",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_categories",
                to="gallery.gallery",
            ),
        ),
    ]
