# Generated by Django 4.1 on 2023-07-03 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        ("blog", "0004_alter_category_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BlogCategory",
        ),
    ]
