# Generated by Django 4.1 on 2023-08-22 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_category_blogcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Specification",
        ),
    ]
