# Generated by Django 4.1 on 2024-05-13 19:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0006_delete_specification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "مقاله", "verbose_name_plural": "مقالات"},
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته های مقاله",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="blog.blogcategory",
                verbose_name="دسته",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="desc",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blogs",
                to="gallery.gallery",
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="زمان انتشار",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="short_desc",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="توضیحات کوتاه"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(max_length=170, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="برچسب ها",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=85, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_categories",
                to="gallery.gallery",
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الویت نمایش"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="blog.blogcategory",
                verbose_name="زیردسته",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
    ]
