# Generated by Django 4.1 on 2023-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_name",
            field=models.CharField(default="hamid", max_length=225),
            preserve_default=False,
        ),
    ]
