# Generated by Django 4.1 on 2024-05-13 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("province", "0002_alter_city_options_alter_province_options_and_more"),
        ("address", "0002_address_full_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "نشانی", "verbose_name_plural": "نشانی ها"},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="province.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="desc",
            field=models.CharField(
                blank=True, max_length=225, null=True, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=225, verbose_name="نام کامل"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="کد پستی"),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="province.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                blank=True, max_length=225, null=True, verbose_name="خیابان"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
