# Generated by Django 4.1 on 2024-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zarinpal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "در حال پرداخت"),
                    (2, "پرداخت انجام شد"),
                    (3, "پرداخت لغو شد"),
                ],
                default=1,
            ),
        ),
    ]
