# Generated by Django 4.1 on 2024-05-13 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0018_alter_category_options_alter_comment_options_and_more"),
        ("zarinpal", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "فاکتور", "verbose_name_plural": "فاکتور ها"},
        ),
        migrations.AlterField(
            model_name="payment",
            name="authority",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="کد پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="desc",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="is_payed",
            field=models.BooleanField(default=False, verbose_name="آیا پرداخت شده؟"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="store.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0,
                default_currency="IRR",
                max_digits=10,
                verbose_name="مبلغ پرداختی",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="شناسه پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "در حال پرداخت"),
                    (2, "پرداخت انجام شد"),
                    (3, "پرداخت لغو شد"),
                ],
                default=1,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
