# Generated by Django 4.1 on 2023-06-10 21:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("text", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "About Us",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("text", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "contactus",
                "verbose_name_plural": "Contact Us",
            },
        ),
    ]
