# Generated by Django 4.1 on 2023-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=72, null=True)),
                ("paragraph", models.CharField(blank=True, max_length=125, null=True)),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "tweeter",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=72, null=True)),
                ("paragraph", models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                "verbose_name": "homeheader",
                "verbose_name_plural": "Home Header",
            },
        ),
        migrations.CreateModel(
            name="SliderAndBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=100, null=True)),
                ("paragraph", models.CharField(blank=True, max_length=125, null=True)),
                ("link_text", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                    ),
                ),
                ("is_slider", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "sliderandbanner",
                "verbose_name_plural": "Slider & Banner",
            },
        ),
    ]
