# Generated by Django 4.1 on 2023-07-01 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0003_footer_is_active_homeheader_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sliderandbanner",
            options={
                "verbose_name": "Slider & Banner",
                "verbose_name_plural": "Slider & Banner",
            },
        ),
    ]
