# Generated by Django 4.1 on 2023-07-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0004_alter_sliderandbanner_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="paragraph",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="homeheader",
            name="paragraph",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
