# Generated by Django 4.1 on 2023-07-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0005_alter_footer_paragraph_alter_homeheader_paragraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=125)),
                ("phone", models.CharField(max_length=11)),
                ("text", models.CharField(max_length=500)),
                ("create_data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
