# Generated by Django 4.1 on 2023-08-21 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0006_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="tweeter",
        ),
    ]
