# Generated by Django 4.1 on 2024-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0008_faqcategory_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAndPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email1", models.EmailField(blank=True, max_length=254, null=True)),
                ("email2", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone1", models.CharField(blank=True, max_length=17, null=True)),
                ("phone2", models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
    ]
