# Generated by Django 4.1 on 2024-05-13 19:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0009_emailandphone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "درباره ما", "verbose_name_plural": "درباره ما"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "تماس با ما", "verbose_name_plural": "تماس با ما"},
        ),
        migrations.AlterModelOptions(
            name="emailandphone",
            options={"verbose_name": "نشانی", "verbose_name_plural": "نشانی ها"},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "سوال", "verbose_name_plural": "سوالات"},
        ),
        migrations.AlterModelOptions(
            name="faqcategory",
            options={
                "verbose_name": "دسته سوالات",
                "verbose_name_plural": "دسته های سوالات",
            },
        ),
        migrations.AlterModelOptions(
            name="footer",
            options={"verbose_name": "فوتر", "verbose_name_plural": "فوتر"},
        ),
        migrations.AlterModelOptions(
            name="homeheader",
            options={
                "verbose_name": "تیتر صفحه اصلی",
                "verbose_name_plural": "تیتر صفحه اصلی",
            },
        ),
        migrations.AlterModelOptions(
            name="sliderandbanner",
            options={
                "verbose_name": "اسلایدر و بنر",
                "verbose_name_plural": "اسلایدر و بنرها",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "تیکت", "verbose_name_plural": "تیکت ها"},
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="متن"
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="title",
            field=models.CharField(max_length=125, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="متن"
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="title",
            field=models.CharField(max_length=125, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="emailandphone",
            name="email1",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="پست الکترونیک اول"
            ),
        ),
        migrations.AlterField(
            model_name="emailandphone",
            name="email2",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="پست الکترونیک دوم"
            ),
        ),
        migrations.AlterField(
            model_name="emailandphone",
            name="phone1",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="شماره تماس اول"
            ),
        ),
        migrations.AlterField(
            model_name="emailandphone",
            name="phone2",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="شماره تماس دوم"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(verbose_name="جواب"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="siteinfo.faqcategory",
                verbose_name="دسته",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=500, verbose_name="سوال"),
        ),
        migrations.AlterField(
            model_name="faqcategory",
            name="title",
            field=models.CharField(max_length=125, verbose_name="دسته بندی"),
        ),
        migrations.AlterField(
            model_name="footer",
            name="heading",
            field=models.CharField(
                blank=True, max_length=72, null=True, verbose_name="تیتر"
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="footer",
            name="paragraph",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="پاراگراف"
            ),
        ),
        migrations.AlterField(
            model_name="homeheader",
            name="header",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=250,
                null=True,
                verbose_name="لینک تیتر",
            ),
        ),
        migrations.AlterField(
            model_name="homeheader",
            name="heading",
            field=models.CharField(
                blank=True, max_length=72, null=True, verbose_name="سر تیتر"
            ),
        ),
        migrations.AlterField(
            model_name="homeheader",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="homeheader",
            name="paragraph",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="توضیح تیتر"
            ),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="heading",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="تیتر"
            ),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="image",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=250,
                null=True,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="is_slider",
            field=models.BooleanField(default=False, verbose_name="آیا اسلایدر هست ؟"),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="link_text",
            field=models.CharField(
                blank=True, max_length=72, null=True, verbose_name="متن لینک"
            ),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="link_url",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=250,
                null=True,
                verbose_name="آدرس لینک",
            ),
        ),
        migrations.AlterField(
            model_name="sliderandbanner",
            name="paragraph",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="پاراگراف"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="create_data",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="full_name",
            field=models.CharField(max_length=125, verbose_name="نام کامل"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="موبایل"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="text",
            field=models.CharField(max_length=500, verbose_name="متن"),
        ),
    ]
